apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-edit
  namespace: api
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: "f7b4f1aa-6371-4308-adc2-30d23b5079a6"
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-view
  namespace: web
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: "f7b4f1aa-6371-4308-adc2-30d23b5079a6"
    apiGroup: rbac.authorization.k8s.io