# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-team2msopenhackkv-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: team2msopenhackKeyVault       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
          objectVersion: ""
    tenantId: 31ac6e3e-689e-4190-ab43-9eec25323e3c                # The tenant ID of the key vault