apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  SQL_USER: sqladminyCc0983
  SQL_PASSWORD: Password123
  SQL_SERVER: sqlserverycc0983.database.windows.net
  SQL_DBNAME: mydrivingDB